version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whaticket
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: whaticket
    command: >
      sh -c "
        echo 'Esperando o MySQL subir...' &&
        sleep 10 &&
        npx sequelize db:migrate &&
        npx sequelize db:seed:all &&
        npm start
      "
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # para evitar sobrescrever os módulos do container
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:8000
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge